"""empty message

Revision ID: dd9aaa5f1378
Revises: 
Create Date: 2024-06-17 02:38:44.511093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9aaa5f1378'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('owner_name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deliver_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Client.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['Food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order')
    op.drop_table('Food')
    op.drop_table('Employee')
    op.drop_table('Recipe')
    op.drop_table('Client')
    op.drop_table('Campaign')
    # ### end Alembic commands ###
